// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiTurnos.Data;

namespace apiTurnos.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200131225819_Creacion de entidades servicios precio v2")]
    partial class Creaciondeentidadesserviciospreciov2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apiTurnos.Models.Empresas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Razon_social")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("apiTurnos.Models.Precio", b =>
                {
                    b.Property<DateTime>("fechahora")
                        .HasColumnType("datetime2");

                    b.Property<float>("importe")
                        .HasColumnType("real");

                    b.Property<int?>("precioid")
                        .HasColumnType("int");

                    b.HasKey("fechahora");

                    b.HasIndex("precioid");

                    b.ToTable("precios");
                });

            modelBuilder.Entity("apiTurnos.Models.Servicios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("servicios");
                });

            modelBuilder.Entity("apiTurnos.Models.Precio", b =>
                {
                    b.HasOne("apiTurnos.Models.Servicios", "precio")
                        .WithMany()
                        .HasForeignKey("precioid");
                });
#pragma warning restore 612, 618
        }
    }
}
